services:
  resume-review-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-review-service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount prompts directory
      - ./prompts:/app/prompts
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
